# Generated by Django 3.1.3 on 2021-01-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopMyBooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
