# Generated by Django 3.1.3 on 2021-01-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopMyBooks', '0002_auto_20210126_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='shop/pics'),
        ),
    ]
