# Generated by Django 3.1.3 on 2021-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughts', models.TextField()),
                ('skills', models.CharField(max_length=50)),
                ('skillper', models.IntegerField(default='')),
                ('projects', models.TextField()),
                ('art_images', models.ImageField(upload_to='shop/pics')),
                ('img_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
