# Generated by Django 3.1.3 on 2021-01-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='art_images',
            field=models.ImageField(blank=True, upload_to='shop/pics'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skillper',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='thoughts',
            field=models.TextField(blank=True),
        ),
    ]
